version: '2'

services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        networks:
            - local-network
        ports:
            - "10001:9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - /home/mark/docker/volumes/portainer_home:/data

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        hostname: jenkins
        # build:
        #     context: .
        #     dockerfile: /jenkins/Dockerfile        
        networks:
            - local-network
        ports:
            - "10003:8080"
            - "50001:50000"      
        volumes:
            - /home/mark/docker/volumes/jenkins_home:/var/jenkins_home
            
    DockerSlave:
        image: liveforensics/dockerslave:latest
        container_name: dockerslave
        hostname: dockerslave
        networks:
            - local-network
        build:
            context: .
            dockerfile: /dockerslave/Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    JenkinsSlave:
        image: liveforensics/jenkinsslave:1.0.0
        container_name: jenkinsslave
        hostname: jenkinsslave
        build:
            context: .
            dockerfile: /jenkinsslave/Dockerfile
        networks:
            - local-network


    # docker run -d --rm -p 10003:8080 -p 50000:50000 
    # -v jenkins_home:/var/jenkins_home 
    # --name jenkins 
    # jenkinsci/blueocean
    # jenkins:
    #     image: jenkinsci/blueocean
    #     container_name: jenkins
    #     networks:
    #         - local-network
    #     ports:
    #         - "10003:8080"
    #         - "50001:50000"
    #     volumes:
    #         - jenkins_home:/var/jenkins_home

    # jenkinsreal:
    #     image: jenkinsci/blueocean
    #     container_name: jenkinsreal
    #     networks:
    #         - local-network
    #     ports:
    #         - "10008:8080"
    #         - "50000:50000"
    #     volumes:
    #         - jenkinsreal_home:/var/jenkins_home            
    # docker run --name splunk -d --rm -p 10002:8000 -p 10005:8088 
    # -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=murraykatt12345' 
    # -v /data/splunk/etc:/opt/splunk/etc -v /data/splunk/var:/opt/splunk/var 
    # splunk/splunk:latest
    # splunk:
    #     image: splunk/splunk:latest
    #     container_name: splunk
    #     networks:
    #         - local-network
    #     ports:
    #         - "10002:8000"
    #         - "10005:8088"
    #     environment:
    #         - SPLUNK_START_ARGS=--accept-license
    #         - SPLUNK_PASSWORD=murraykatt12345
    #     volumes:
    #         - "/data/splunk/etc:/opt/splunk/etc"
    #         - "/data/splunk/var:/opt/splunk/var"
                    
networks:
    local-network:
        driver: bridge
        
# volumes:
#     jenkins_home:
#     portainer_data:
#     jenkinsreal_home: