version: '2'

services:
    # node:
        # build:
            # context: .
            # dockerfile: node.dockerfile
        # ports:
            # - "10006:3000"
        # networks:
            # - nodeapp-network
            
    # mongodb:
        # image: mongo
        # networks:
            # - nodeapp-network
            
    # docker run --restart unless-stopped --name mailhog -p 1025:1025 -p 8025:8025 -d --rm mailhog/mailhog
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        networks:
            - nodeapp-network
        ports:
            - "10006:1025"
            - "10007:8025"
    # docker run -d -p 10001:9000 --name portainer -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
    portainer:
        image: portainer/portainer
        container_name: portainer
        networks:
            - nodeapp-network
        ports:
            - "10001:9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - portainer_data:/data
            
    # docker run -d --rm -p 10003:8080 -p 50000:50000 
    # -v jenkins_home:/var/jenkins_home 
    # --name jenkins 
    # jenkinsci/blueocean
    jenkinstest:
        image: jenkinsci/blueocean
        container_name: jenkinstest
        networks:
            - nodeapp-network
        ports:
            - "10003:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
    # docker run --name splunk -d --rm -p 10002:8000 -p 10005:8088 
    # -e 'SPLUNK_START_ARGS=--accept-license' -e 'SPLUNK_PASSWORD=murraykatt12345' 
    # -v /data/splunk/etc:/opt/splunk/etc -v /data/splunk/var:/opt/splunk/var 
    # splunk/splunk:latest
    splunktest:
        image: splunk/splunk:latest
        container_name: splunktest
        networks:
            - nodeapp-network
        ports:
            - "10002:8000"
            - "10005:8088"
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=murraykatt12345
        volumes:
            - "/data/splunk/etc:/opt/splunk/etc"
            - "/data/splunk/var:/opt/splunk/var"
                    
networks:
    nodeapp-network:
        driver: bridge
        
volumes:
    jenkins_home:
    portainer_data: