version: '2'

services:
    node:
        build:
            context: .
            dockerfile: node.dockerfile
        ports:
            - "10006:3000"
        networks:
            - nodeapp-network
            
    mongodb:
        image: mongo
        networks:
            - nodeapp-network

networks:
    nodeapp-network:
        driver: bridge
        