pipeline {
    agent {
        node {
            label 'WindowsOne'
        }
    }
    stages {
        stage('Preparation') {
            steps {
                git 'https://github.com/microsoft/VCSamples.git'
                
                
            }
        }
        stage('Builder') {
            steps {
                echo 'do some build magic'
                dir('VC2015Samples\\scribble') {                    
                    script {                    
                        bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat && msbuild.exe scribble.sln' 
                    }
                }
                
                // bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat'
                

                // powershell 'msbuild --version'
            
            }
        }
    }
    
}
