echo 'welcome to my test pipeline'
pipeline {
  agent any
    parameters {
        string(name: 'GIT_PROJECT_NAME', defaultValue: '', description: 'Which project would you like to build?')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'master', description: 'Which branch would you like to build?')
        string(name: 'AUTHOR_NAME', defaultValue: 'wer', description: 'Please enter your name')
    }
  stages {
    stage('Gittery') {
      steps {
        echo "git url is ${GIT_PROJECT_NAME}"
        echo "git url is ${GIT_BRANCH_NAME}"
        echo "author is ${AUTHOR_NAME}"
        cleanWs()
        git branch: "${GIT_BRANCH_NAME}", url: "${GIT_PROJECT_NAME}"
      }
    }
    stage('Call Test') {
      steps {
        sh 'ls -ahl'
      }
    }
    // stage('Buildery') {
    //   steps {
    //     bat 'c:\\tools\\nuget.exe restore MyClasses.sln'
		//     bat "\"${tool 'VS2017'}\" MyClasses.sln /p:Configuration=Debug /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"
    //   }
    // }
	  // stage('Testery') {	
		//   steps {
		//     dir('MyClassesTest\\bin\\debug') {
		//   	  bat "\"${tool 'VSTEST'}\"vstest.console.exe MyClassesTest.dll /EnableCodeCoverage /Logger:trx"
	  // 	  }
	  // 	}
	  // }
  }
  environment {
    test = '1'
  }
}

