echo 'welcome to my test pipeline'
pipeline {
  agent any
    parameters {
        string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet the world?')
    }
  stages {
    stage('Gittery') {
      steps {
        echo "git url is ${GIT_PROJECT_NAME}"
        cleanWs()
      }
    }
    stage('Call Test') {
      steps {
        sh 'ls -ahl'
      }
    }
    // stage('Buildery') {
    //   steps {
    //     bat 'c:\\tools\\nuget.exe restore MyClasses.sln'
		//     bat "\"${tool 'VS2017'}\" MyClasses.sln /p:Configuration=Debug /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"
    //   }
    // }
	  // stage('Testery') {	
		//   steps {
		//     dir('MyClassesTest\\bin\\debug') {
		//   	  bat "\"${tool 'VSTEST'}\"vstest.console.exe MyClassesTest.dll /EnableCodeCoverage /Logger:trx"
	  // 	  }
	  // 	}
	  // }
  }
  environment {
    test = '1'
  }
}

