pipeline {
    agent {
        node {
            label 'ppc'
        }
    }
    stages {
        stage('Preparation') {
            steps {
                echo 'do some prep'
                
                
            }
        }
        stage('Builder') {
            steps {                  
                script {
                    def msg = powershell(returnStdout: true, script: 'Write-Output "PowerShell is mighty!"')
                    println msg
                }                 
                
                                                                                           
            }
        }
    }
    
}
