pipeline {
    agent {
        node {
            label 'ppc'
        }
    }
    stages {
        stage('Preparation') {
            steps {
                echo 'do some prep'
                
                
            }
        }
        stage('Builder') {
            steps {
                step {
                    echo 'do some build magic'
                    def msg = powershell(returnStdout: true, script: 'Write-Output "PowerShell is mighty!"')
                    println msg
                }
                
                
                
                
                // bat 'call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat'
                

                // powershell 'msbuild --version'
            
            }
        }
    }
    
}
